service: helloworld-typescript

provider:
  name: aws
  runtime: nodejs12.x

functions:
  helloWorldFunction:
    handler: index.handler
    name: helloworld-typescript
    events:
      -http: GET hello
